apiVersion: v1 # String
kind: Pod # String
metadata: # Dictionary
  name: myapp-pod
  labels: # Dictionary
    app: myapp # Key value paids
spec:
  containers: # List
  - name: myapp
    image: hriyen777/acr-myindia-app:v1
    ports:
    - containerPort: 80



