apiVersion: apps/v1
kind: ReplicaSet
metadata: #Dictionary
  name: myapp2-rs
spec: # Dictionary
  replicas: 3
  selector:
    matchLabels:
      app: myapp2
  template:
    metadata: # Dictionary
      name: myapp2-pod
      labels: # Dictionary
        app: myapp2 # Key value paids
    spec:
      containers: # List
      - name: myapp2-container
        image: hriyen777/acr-myindia-app:v1
        ports:
        - containerPort: 80

